# /// script
# requires-python = ">=3.11"
# dependencies = ["openpyxl>=3.1"]
# ///
# scripts/_common.py
"""Shared helpers for dmac-curation build scripts.

This module is a LIBRARY. It holds nothing project-specific: no filenames, no
person names, no UID tables, no manuscript section titles. Everything that
varies per project lives in the project's lockfile and reaches scripts via
``scripts/_config.py`` (toolkit spec P2/P3).

Provides:
  - ``mint_uid(sample_type, lab, date, n)`` -> canonical ``<TYPE>-YYMMDD<LAB>-N``
  - ``join_uids(uids)`` -> ``"A;B"`` for Parent-style cells (no space; NExtSEEK
    canonicalises to this form, so emitting ``"; "`` breaks round-trip diffs)
  - ``placeholder(what)`` -> the greppable ``*** PLACEHOLDER: ... ***`` marker
  - ``sampletype_schema(sampletype, catalog=None)`` -> the catalog record
  - ``schema_column_order(schema, samples)`` -> UID, schema fields, then extras
  - ``write_4sheet_xlsx(...)`` -> the Instructions/Samples/Assay/Ontology writer
  - CSV and master-workbook readers, and a generic UID-map handoff

Per-project ``build_<arm>.py`` scripts generated by ``/curate-build`` import
from here via a ``sys.path`` insert of the plugin's ``scripts/`` directory.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from openpyxl import Workbook, load_workbook

# SKILL.md hard rule 8: unknown values get a greppable marker, never a blank.
PLACEHOLDER = "*** PLACEHOLDER:"


def placeholder(what: str) -> str:
    """Build the standard placeholder marker: ``*** PLACEHOLDER: <what> ***``."""
    return f"{PLACEHOLDER} {what} ***"


# ---------------------------------------------------------------------------
# UID minting
# ---------------------------------------------------------------------------
def join_uids(uids) -> str:
    """Join UIDs for a ``Parent``-style cell: semicolon, NO space.

    NExtSEEK canonicalises multi-value UID lists to ``"A;B"`` on insert. Emitting
    ``"; "`` uploads fine but comes back different, so every multi-parent row
    reports a false diff in ``/curate-validate``. Build scripts should route all
    UID-list cells through here so the sheet matches what the DB will store.

    Blank/None entries are dropped; order is preserved.
    """
    return ";".join(str(u).strip() for u in uids if u is not None and str(u).strip())


def mint_uid(sample_type: str, lab: str, date: str, n: int) -> str:
    """Canonical 4-arg UID minter: ``mint_uid('RNA', 'KAM', '260527', 1)``
    -> ``'RNA-260527KAM-1'``.

    This is the universal UID format documented in SKILL.md: ``<TYPE>-YYMMDD<LAB>-N``.

    Args:
      sample_type: SampleType abbreviation, e.g. ``'OOC'``, ``'D.SEQ'``.
      lab:         Lab code suffix, e.g. ``'KAM'``, ``'ENG'``.
      date:        6-digit YYMMDD string, e.g. ``'260527'``.
      n:           Integer counter (1-based).
    """
    return f"{sample_type}-{date}{lab}-{n}"


# ---------------------------------------------------------------------------
# Generic tabular loaders — all take explicit paths
# ---------------------------------------------------------------------------
def load_manifest(path: Path) -> list[dict]:
    """Read a manifest CSV; caller filters."""
    with Path(path).open() as f:
        return list(csv.DictReader(f))


def load_omero(path: Path) -> dict[str, dict]:
    """Map filename -> omero row dict from an omero_images.csv."""
    with Path(path).open() as f:
        return {r["filename"]: r for r in csv.DictReader(f)}


def load_master_workbook(path: Path) -> dict[str, list[dict]]:
    """Read a denormalized master xlsx into ``{sheet_name: [row dicts]}``.

    Build scripts use this to look up existing rows whose UID they cite as a
    Parent, and to sample real observed values before inventing a new term.
    SKILL.md hard rule 4: schema lies, workbook tells truth.
    """
    wb = load_workbook(path, read_only=True, data_only=True)
    try:
        out: dict[str, list[dict]] = {}
        for sheet in wb.sheetnames:
            ws = wb[sheet]
            rows = list(ws.iter_rows(values_only=True))
            if not rows:
                out[sheet] = []
                continue
            headers = [h or f"_col{i}" for i, h in enumerate(rows[0])]
            out[sheet] = [
                {h: v for h, v in zip(headers, row) if v is not None}
                for row in rows[1:]
            ]
        return out
    finally:
        wb.close()


def master_lookup(master: dict[str, list[dict]], sheet: str, uid: str) -> dict | None:
    """Find a row by UID on one sheet of a loaded master workbook."""
    for r in master.get(sheet, []):
        if r.get("UID") == uid:
            return r
    return None


def master_vocab(master: dict[str, list[dict]], sheet: str,
                 fields: list[str]) -> dict[str, set[str]]:
    """Distinct observed values per field on one sheet — real values beat guesses."""
    vocab: dict[str, set[str]] = {f: set() for f in fields}
    for r in master.get(sheet, []):
        for f in fields:
            v = r.get(f)
            if v is not None and str(v).strip():
                vocab[f].add(str(v).strip())
    return vocab


# ---------------------------------------------------------------------------
# UID map (cross-script handoff within one project)
# ---------------------------------------------------------------------------
def save_uid_map(path: Path, mapping: dict[str, str]) -> None:
    """Persist a {natural key -> UID} map for a later build script to read."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(mapping, indent=2, sort_keys=True))


def load_uid_map(path: Path) -> dict[str, str]:
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run the build script that produces it first."
        )
    return json.loads(path.read_text())


# ---------------------------------------------------------------------------
# SampleType catalog lookup
# ---------------------------------------------------------------------------
def sampletype_schema(sampletype: str, catalog: Path | None = None) -> dict:
    """Return the catalog record for a sample type.

    Args:
      sampletype: short code, e.g. ``'MUS'``.
      catalog:    explicit ``sampletypes_db.json``. Defaults to the plugin's
                  bundled read-only copy.
    """
    if catalog is None:
        import sys
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from _config import plugin_context
        catalog = plugin_context("sampletypes_db.json")
    db = json.loads(Path(catalog).read_text())
    for r in db:
        if r.get("SampleType") == sampletype:
            return r
    raise KeyError(f"SampleType {sampletype!r} not found in {catalog}")


def schema_column_order(schema: dict, samples: list[dict]) -> list[str]:
    """Column order for the Samples sheet: UID, then the catalog's declared
    fields in Required/Standard/Possible order, then any denormalized extras.

    This is the genuinely shared, schema-driven capability that survived the
    P3 de-projecting.
    """
    all_keys: list[str] = ["UID"]
    seen: set[str] = {"UID"}
    for src in ("Required Metadata", "Standard Metadata", "Possible Metadata Fields"):
        for k in (schema.get(src) or "").split(","):
            k = k.strip()
            if k and k not in seen:
                all_keys.append(k)
                seen.add(k)
    for s in samples:
        for k in s.keys():
            if k not in seen:
                all_keys.append(k)
                seen.add(k)
    return all_keys


# ---------------------------------------------------------------------------
# 4-sheet xlsx writer (Instructions / Samples / Assay / Ontology)
# ---------------------------------------------------------------------------
def write_4sheet_xlsx(
    out_path: Path,
    sampletype: str,
    samples: list[dict],
    assay_titles: list[str],
    ontology: dict[str, list[str]] | None = None,
    catalog: Path | None = None,
) -> None:
    """Emit the standard 4-sheet structure NExtSEEK auto-detects.

    Args:
      out_path:     target file (parents are created).
      sampletype:   SampleType abbreviation, e.g. ``'OOC'``.
      samples:      row dicts keyed by catalog field names (case-sensitive).
                    ``'UID'`` is required even if blank.
      assay_titles: assay title strings to register on the Assay sheet.
      ontology:     ``{fieldname: [allowed values]}`` for the Ontology sheet.
                    Fields appearing here are declared ``Controlled Ontology``
                    on the Instructions sheet; everything else is ``Text``.
                    Ontology validation is STRICT and exists ONLY in this
                    4-sheet format — the flat format has no Ontology sheet and
                    silently discards an ontology column.
      catalog:      explicit sampletypes_db.json; defaults to the plugin's.

    The Samples sheet uses one column per distinct field key across all rows,
    so missing fields produce empty cells, NOT ``'null'``/``'None'``.
    """
    schema = sampletype_schema(sampletype, catalog=catalog)
    all_keys = schema_column_order(schema, samples)
    ontology = ontology or {}

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    # --- Instructions ------------------------------------------------------
    ws = wb.active
    ws.title = "Instructions"
    ws.append(["Field", "Database Field", "Field Type", "Ontology"])
    for k in all_keys:
        if k in ontology:
            ws.append([k, f"{sampletype}::{k}", "Controlled Ontology", k])
        else:
            ws.append([k, f"{sampletype}::{k}", "Text", ""])
    # --- Samples -----------------------------------------------------------
    ws = wb.create_sheet("Samples")
    ws.append(all_keys)
    for s in samples:
        ws.append([s.get(k, "") for k in all_keys])
    # --- Assay -------------------------------------------------------------
    ws = wb.create_sheet("Assay")
    ws.append(["SampleType", "AssayType", "Assay", "Direction"])
    for t in assay_titles:
        ws.append([sampletype, "", t, "child"])
    # --- Ontology ----------------------------------------------------------
    ws = wb.create_sheet("Ontology")
    ws.append(["Field", "Value"])
    for field_name, values in ontology.items():
        for v in values:
            ws.append([field_name, v])
    wb.save(out_path)
