#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["openpyxl>=3.1"]
# ///
"""
Consolidate the 20 per-sample-type 4-sheet xlsx files in assay_sheets/ into
5 per-arm flat-format xlsx files for NExtSEEK batch upload.

Per /nextseek_api/batch-upload/start/ spec:

  Flat Format (single sheet):
    - uid              -- Sample UID. Leave empty for auto-generation.
    - sampletype       -- Sample type name (alias: sample_type)
    - json_metadata    -- JSON metadata string with all sample attributes
    - assay_ids        -- Comma-separated assay IDs (alias: assayids)
    - Optional: project_id, study_title, study_id, sop_id, assay_titles

  When file has all 4 sheet names (Instructions/Samples/Assay/Ontology),
  the 4-sheet format is auto-detected; otherwise flat. Multiple sample types
  in one file are ONLY allowed in flat format.

Output is named `Arm{X}-upload.xlsx` — the `-upload` suffix the downstream
retrieve and deposit steps read, so no rename is needed between here and
Phase 11. (`--all-in-one NAME` still writes exactly `NAME.xlsx`.)

Output (5 files):
  ArmA-upload.xlsx — 117 rows: RNA, DNA, D.SEQ, D.MSP (phospho), D.IMG (H&E)
  ArmB-upload.xlsx —  74 rows: CEL, MUS, TIS, D.MSP (mouse cell-line MHC)
  ArmE-upload.xlsx —  78 rows: PAT, PAV, TIS, CEL, MUS, D.MSP (human PDX)
  ArmF-upload.xlsx —  96 rows: PAT, PAV, TIS, D.MSP (human patient)
  ArmH-upload.xlsx —   2 rows: D.REF (SDA databases)

Each output file contains one "Samples" sheet with columns:
  - uid, sampletype                         (required by NExtSEEK)
  - name, parent                            (denormalized, for at-a-glance review;
                                             NExtSEEK ignores these as unknown columns)
  - notes_summary                           (denormalized, first 80 chars of Notes)
  - json_metadata                           (canonical upload payload — all sample
                                             attributes serialized as compact JSON)
  - assay_titles                            (parent assay name from the original
                                             4-sheet Assay tab)

Alongside each flat upload file, a companion `<arm>_review.xlsx` is written with
ONE SHEET PER SAMPLE TYPE and every field in its own column. The flat file packs
each sample into a single `json_metadata` blob — correct for upload, unreadable
for a human — so the review file is what a curator actually reads before
submitting. It is never uploaded.

The 20 original per-sample-type xlsx files are moved to
  assay_sheets/4sheet_originals/
for reference (in case the schema-level review benefits from the per-type
Instructions docs).
"""

import os
import re
import sys
import json
import shutil
from pathlib import Path
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from collections import defaultdict

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _config import add_config_args, config_from_args, plugin_root  # noqa: E402
from _config import ProjectRootError  # noqa: E402

HDR_FILL = PatternFill("solid", fgColor="D9E1F2")
HDR_FONT = Font(bold=True)

# Assay-ID resolution: two layers.
#
#  1. context/assay_ids_cache.json — auto-generated by
#     `scripts/nextseek_api.py fetch-assays --project-id <ID>`.
#     Maps {assay_title: assay_id} as actually registered in the target
#     project. Refresh whenever switching projects or when the project's
#     assay catalog changes.
#
#  2. context/assay_synonyms.json — CURATED by an LLM/human after each
#     cache refresh. Maps {cited_assay_name: project_actual_name} for
#     cases where our build scripts use a generic semantic name (e.g.
#     "Mass Spectrometry Proteomics") but the project catalog uses a
#     different title (e.g. "Proteomics"). Reasoning lives in the JSON's
#     _notes block.
#
# Resolution order for any cited assay title:
#   (a) direct hit in the cache
#   (b) apply synonym → re-hit cache
#   (c) leave assay_ids blank (assay_titles still emitted)
#
# Assay IDs are PROJECT-SCOPED — the same title maps to different IDs
# across projects. Always re-run the fetch + re-review synonyms when
# switching projects. See Q S3 in QUESTIONS_FOR_YUFEI.md.

def _load_assay_id_lookup(context_dir):
    """Returns (lookup_dict, synonyms_dict, source_description).

    Reads the PROJECT's context/ (resolved from cwd, never the plugin).
    """
    cache_path = Path(context_dir) / "assay_ids_cache.json"
    synonyms_path = Path(context_dir) / "assay_synonyms.json"
    lookup = {}
    synonyms = {}
    sources = []

    if cache_path.exists():
        try:
            cache = json.loads(cache_path.read_text())
            lookup = cache.get("assay_id_by_title") or {}
            sources.append(f"cache {cache_path.name} "
                           f"(project {cache.get('project_id')!r}, "
                           f"{len(lookup)} assays, fetched "
                           f"{cache.get('fetched_at_utc', '?')})")
        except (OSError, json.JSONDecodeError) as e:
            sources.append(f"cache UNREADABLE: {e}")
    else:
        sources.append("no cache (run scripts/nextseek_api.py fetch-assays)")

    if synonyms_path.exists():
        try:
            syn_doc = json.loads(synonyms_path.read_text())
            synonyms = syn_doc.get("synonyms_by_cited_name") or {}
            sources.append(f"synonyms {synonyms_path.name} "
                           f"({len(synonyms)} mappings)")
        except (OSError, json.JSONDecodeError) as e:
            sources.append(f"synonyms UNREADABLE: {e}")
    else:
        sources.append("no synonyms file")

    return lookup, synonyms, " + ".join(sources)


def resolve_assay_id(cited_name, lookup, synonyms):
    """Resolve a cited assay title to (resolved_title, assay_id_or_None).

    `resolved_title` is what we emit in the `assay_titles` column; either
    the cited name (if found directly in cache) or the synonym (if mapped).
    """
    if not cited_name:
        return "", None
    if cited_name in lookup:
        return cited_name, lookup[cited_name]
    if cited_name in synonyms:
        canonical = synonyms[cited_name]
        if canonical in lookup:
            return canonical, lookup[canonical]
    # No mapping; emit cited title with no ID (upload tool can flag or admin can patch)
    return cited_name, None

# ─── Read one 4-sheet xlsx → flat records ──────────────────────────────────

def read_4sheet(path):
    """Return (sampletype, [records]) — records are dicts of column→value."""
    wb = openpyxl.load_workbook(path, data_only=True)

    # Sample type from Instructions sheet (Database Field has 'SampleType::AttrName')
    instr = wb["Instructions"]
    sampletype = None
    for r in instr.iter_rows(min_row=2, values_only=True):
        if r and len(r) > 1 and r[1]:
            sampletype = str(r[1]).split("::")[0]
            break

    # Parent assay (first row of Assay sheet). Ignore parenthesized placeholders
    # like "(visit registration)" — those aren't real NExtSEEK assay names.
    #
    # Two schemas in the wild:
    #   CSBC:       columns = (SampleType, Role, AssayTitle, ...)  with Role=='Parent'
    #   IntravChip: columns = (SampleType, AssayType, Assay, Direction) with
    #               Direction=='child' (the sample is a child of the assay)
    # In both cases the assay title is in column[2]; the IntravChip files don't
    # have a 'Parent' literal anywhere, so we accept either ('Parent' in col 1)
    # or any row whose col 2 is a real assay name.
    parent_assay = ""
    if "Assay" in wb.sheetnames:
        for r in wb["Assay"].iter_rows(min_row=2, values_only=True):
            if r and len(r) >= 3 and r[2]:
                candidate = str(r[2]).strip()
                if candidate and not candidate.startswith("("):
                    parent_assay = candidate
                    break

    # Sample rows
    samples = wb["Samples"]
    rows_iter = samples.iter_rows(values_only=True)
    headers = next(rows_iter)
    records = []
    for r in rows_iter:
        if not any(v not in (None, "") for v in r):
            continue
        rec = {h: v for h, v in zip(headers, r) if v not in (None, "")}
        records.append(rec)

    wb.close()
    return sampletype, parent_assay, records

# ─── Build the human-review workbook (one sheet per sample type) ───────────

def build_review_workbook(arm_name, source_files, out_dir):
    """Emit `<arm>_review.xlsx`: one sheet per SAMPLE TYPE, every field its own column.

    The flat upload file carries each sample as a single `json_metadata` blob, which is
    what NExtSEEK wants and what a human cannot read. This is the reviewable twin: the
    same records, re-expanded, split the way the curator thinks about them.

    Kept as a SEPARATE FILE rather than an extra sheet so the upload workbook stays
    exactly what gets submitted, with nothing extra in it.

    A sample type split across several source files (e.g. A.TITR appearing in both an
    arm build and a published-data build) is MERGED into one sheet — the sheet is per
    sample type, not per source file.
    """
    by_type = defaultdict(list)
    for sampletype, _, records in source_files:
        by_type[sampletype].extend(records)

    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    for sampletype in sorted(by_type):
        records = by_type[sampletype]
        # Identity first, then every other field in order of first appearance, so
        # related fields stay adjacent instead of being alphabetised apart.
        lead = [c for c in ("UID", "Name", "Parent") if any(c in r for r in records)]
        seen, rest = set(lead), []
        for rec in records:
            for k in rec:
                if k not in seen:
                    seen.add(k)
                    rest.append(k)
        cols = lead + rest

        # Excel sheet names cap at 31 chars and forbid []:*?/\
        title = re.sub(r"[\[\]:*?/\\]", "-", sampletype)[:31]
        ws = wb.create_sheet(title)
        ws.append(cols)
        for cell in ws[1]:
            cell.fill = HDR_FILL
            cell.font = HDR_FONT
        for rec in records:
            ws.append([rec.get(c, "") for c in cols])

        for i, col in enumerate(cols, 1):
            # Parent can hold hundreds of semicolon-joined UIDs; bound it so it cannot
            # push every other column off screen.
            width = {"UID": 24, "Name": 34, "Parent": 45}.get(col, 22)
            ws.column_dimensions[get_column_letter(i)].width = width
        ws.freeze_panes = "B2"

    out = out_dir / f"{arm_name}_review.xlsx"
    wb.save(out)
    return out, {st: len(r) for st, r in by_type.items()}


# ─── Build one flat-format xlsx for an arm ─────────────────────────────────

def build_arm_flat(arm_name, source_files, out_dir, lookup, synonyms, out_name):
    """source_files: list of (sampletype, parent_assay, [records]).

    `out_name` is the output basename (e.g. ``ArmA-upload.xlsx``); the caller
    decides it so per-arm and ``--all-in-one`` runs can name files differently.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Samples"

    flat_cols = ["uid", "sampletype", "name", "parent",
                 "notes_summary", "assay_titles", "assay_ids", "json_metadata"]
    ws.append(flat_cols)
    for cell in ws[1]:
        cell.fill = HDR_FILL
        cell.font = HDR_FONT

    total = 0
    for sampletype, parent_assay, records in source_files:
        # Resolve cited assay title → (canonical title, ID) via cache+synonyms
        resolved_title, assay_id_val = resolve_assay_id(parent_assay, lookup, synonyms)
        assay_ids_cell = str(assay_id_val) if assay_id_val is not None else ""

        for rec in records:
            # NExtSEEK expects UID inside json_metadata (verified by validate
            # endpoint dry-run). Keep it in the dict; ALSO emit at the
            # top-level `uid` column so both shapes are populated.
            uid = rec.get("UID", "")
            name = rec.get("Name", "")
            parent = rec.get("Parent", "")
            notes = rec.get("Notes", "")
            notes_summary = (notes[:80] + "…") if len(str(notes)) > 80 else notes

            # json_metadata: all attributes as compact JSON (INCLUDING UID)
            json_meta = json.dumps(rec, separators=(",", ":"), default=str)

            ws.append([uid, sampletype, name, parent, notes_summary,
                       resolved_title, assay_ids_cell, json_meta])
            total += 1

    # Column widths tuned for readability
    widths = {"uid": 24, "sampletype": 12, "name": 30, "parent": 24,
              "notes_summary": 50, "assay_titles": 30, "assay_ids": 10,
              "json_metadata": 80}
    for i, col in enumerate(flat_cols, 1):
        ws.column_dimensions[get_column_letter(i)].width = widths.get(col, 16)

    # Wrap notes_summary so the row doesn't blow up
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    # README sheet — quick orientation
    readme = wb.create_sheet("README")
    readme.append(["NExtSEEK batch upload — flat format"])
    readme.append([])
    readme.append([f"Arm: {arm_name}"])
    readme.append([f"Total rows: {total}"])
    readme.append([f"Sample types: {', '.join(st for st, _, _ in source_files)}"])
    readme.append([])
    readme.append(["Columns:"])
    readme.append(["  uid             — pre-assigned UID (NExtSEEK will validate)"])
    readme.append(["  sampletype      — NExtSEEK sample-type short code (MUS, TIS, RNA, D.SEQ, …)"])
    readme.append(["  name            — DENORMALIZED for review; same as json_metadata['Name']"])
    readme.append(["  parent          — DENORMALIZED for review; same as json_metadata['Parent']"])
    readme.append(["  notes_summary   — DENORMALIZED first 80 chars of json_metadata['Notes']"])
    readme.append(["  assay_titles    — Parent assay name (human-readable)"])
    readme.append(["  assay_ids       — Internal Assay ID where available in local assays_db.json"])
    readme.append(["                    (RNA Extraction=61, Tissue Collection=74, Short Read Sequencing=64,"])
    readme.append(["                     Cell Culture=85; others blank — see Q S3 in QUESTIONS_FOR_YUFEI.md)"])
    readme.append(["  json_metadata   — UPLOAD PAYLOAD: full per-sample attributes as compact JSON"])
    readme.append([])
    readme.append(["Companion file:"])
    readme.append([f"  {arm_name}_review.xlsx — THE SAME ROWS, one sheet per sample type,"])
    readme.append(["      every field in its own column. Read that one to review the metadata;"])
    readme.append(["      upload THIS one. The review file is never submitted."])
    readme.append([])
    readme.append(["NOTE: NExtSEEK reads uid, sampletype, json_metadata, plus EITHER assay_ids OR"])
    readme.append(["      assay_titles (both are in the InputRowModel schema, but the spec does NOT"])
    readme.append(["      explicitly say whether the server auto-resolves titles → IDs). Both columns"])
    readme.append(["      are included here; the upload tool can use whichever it prefers and the"])
    readme.append(["      unused one is ignored (per the 'unknown columns ignored with warning' rule)."])
    readme.append(["      The denormalized columns (name/parent/notes_summary) are for human review"])
    readme.append(["      only and are also silently ignored on upload."])
    readme.column_dimensions['A'].width = 100
    for cell in readme['A']:
        cell.alignment = Alignment(wrap_text=True)
    readme['A1'].font = Font(bold=True, size=14)

    out = out_dir / out_name
    wb.save(out)
    return out, total

# ─── Guard ────────────────────────────────────────────────────────────────

def is_consolidated_output(name):
    """True for a per-arm flat file this script OWNS and may delete before a
    re-run: the underscore-free outputs it writes (``ArmA-upload.xlsx``) plus
    legacy bare-arm outputs (``ArmA.xlsx``) from before the ``-upload`` suffix.

    A ``-upload-new.xlsx`` is NEVER an output we own: it is the curator's
    protected working copy (hard rule 2), carrying hand edits and GEO/Zenodo
    backfill that a regeneration would silently destroy. So we keep it even
    though it is also underscore-free. 4-sheet sources (``ArmA_RNA.xlsx``, with
    an underscore) and openpyxl lock files (``~$…``) are likewise not ours.
    """
    if not name.endswith(".xlsx") or name.startswith("~"):
        return False
    if "_" in name:            # a 4-sheet source, not a consolidated output
        return False
    if "-upload-new" in name:  # the protected working copy — never delete
        return False
    return True


def _is_inside_plugin(path, plugin=None):
    """True if `path` is the plugin checkout itself or lives inside its tree.

    The consolidate step DELETES every underscore-free ``.xlsx`` from its target
    directory (and moves originals around), so it must refuse a target that is
    the plugin root or anything under it — e.g. a curator who points
    ``--assay-sheets`` at the plugin's own ``assay_sheets`` from a legitimate
    project cwd, where ``find_project_root`` would not otherwise raise. The path
    is resolved first so ``..`` / symlink dodges still land inside the subtree.
    """
    plugin = (plugin_root() if plugin is None else Path(plugin)).resolve()
    path = Path(path).resolve()
    return path == plugin or plugin in path.parents


# ─── Main ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    add_config_args(parser)
    parser.add_argument(
        "--assay-sheets", type=Path, default=None,
        help="Directory holding the 4-sheet inputs and receiving the flat "
             "outputs (default: <project-root>/assay_sheets)",
    )
    parser.add_argument(
        "--all-in-one", metavar="NAME", default=None,
        help="Consolidate ALL 4-sheet inputs into a single flat output named "
             "NAME.xlsx, rather than grouping by filename prefix (the default "
             "per-arm CSBC behavior). Use this for single-project uploads "
             "(e.g. --all-in-one IntravChip_upload).",
    )
    args = parser.parse_args()

    try:
        cfg = config_from_args(args)
    except ProjectRootError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)

    src = Path(args.assay_sheets).resolve() if args.assay_sheets else cfg.assay_sheets
    arch = src / "4sheet_originals"

    # Refuse to touch the plugin checkout. This script DELETES underscore-free
    # .xlsx from `src` and moves originals around, so a `src` at or under the
    # plugin root (e.g. --assay-sheets <plugin>/assay_sheets, run from a real
    # project so ProjectRootError never fired) must be rejected up-front, before
    # any filesystem mutation. (Replaces a tautological assert; see Task 8 review.)
    if _is_inside_plugin(src):
        print(f"error: refusing to operate inside the plugin checkout ({src})",
              file=sys.stderr)
        raise SystemExit(2)

    if not src.is_dir():
        print(f"ERROR: {src} is not a directory", file=sys.stderr)
        raise SystemExit(2)

    lookup, synonyms, source_desc = _load_assay_id_lookup(cfg.context)
    print(f"Project root:    {cfg.root}")
    print(f"Assay sheets:    {src}")
    print(f"Assay-ID source: {source_desc}\n")

    # Source dir resolution: prefer 4sheet_originals/ if it exists with files
    # (subsequent runs), otherwise read from assay_sheets/ root (first run).
    # Only pick up files that look like 4-sheet sources (have an underscore in
    # the filename, e.g. ArmA_RNA.xlsx; consolidated outputs like ArmA.xlsx
    # don't have one).
    def is_4sheet_filename(name):
        return name.endswith(".xlsx") and not name.startswith("~") and "_" in name

    if os.path.isdir(arch) and any(is_4sheet_filename(f) for f in os.listdir(arch)):
        source_dir = arch
        print(f"Reading 4-sheet sources from {arch}/ (archive)")
    else:
        source_dir = src
        print(f"Reading 4-sheet sources from {src}/ (first-run mode)")

    files = sorted(f for f in os.listdir(source_dir) if is_4sheet_filename(f))
    if not files:
        print(f"  ERROR: no 4-sheet files found in {source_dir}", file=sys.stderr)
        raise SystemExit(1)

    by_arm = defaultdict(list)  # 'ArmA' → [(path, ...)]
    if args.all_in_one:
        # Single-bucket mode: every input feeds the same output.
        for f in files:
            by_arm[args.all_in_one].append(str(source_dir / f))
    else:
        for f in files:
            arm = f.split("_")[0]
            by_arm[arm].append(str(source_dir / f))

    # Clean any prior consolidated outputs so we don't mix old + new — but keep
    # `-upload-new.xlsx` working copies (see is_consolidated_output).
    # (A `src` at or under the plugin checkout was already rejected up-front.)
    for f in os.listdir(src):
        if is_consolidated_output(f):
            os.remove(src / f)

    # Archive originals (only if reading from src root; otherwise they're already archived)
    os.makedirs(arch, exist_ok=True)
    if source_dir == src:
        print(f"Archiving {len(files)} four-sheet originals to {arch}/")
    print()

    arm_outputs = []
    for arm in sorted(by_arm):
        # Load all sub-files for this arm
        sources = []
        for path in by_arm[arm]:
            st, pa, recs = read_4sheet(path)
            sources.append((st, pa, recs))
        # Build consolidated flat file. Per-arm outputs carry the `-upload`
        # suffix retrieve/deposit read; --all-in-one keeps the exact NAME given.
        out_name = f"{arm}.xlsx" if args.all_in_one else f"{arm}-upload.xlsx"
        out, n = build_arm_flat(arm, sources, src, lookup, synonyms, out_name)
        review_out, review_counts = build_review_workbook(arm, sources, src)
        arm_outputs.append((out, n, len(by_arm[arm]), review_out, review_counts))

    # Move originals to archive AFTER reading (only if we read from src root —
    # otherwise they're already in arch).
    if source_dir == src:
        for f in files:
            shutil.move(str(src / f), str(arch / f))

    print("Consolidated:")
    for out, n, src_count, review_out, review_counts in arm_outputs:
        print(f"  ✓ {os.path.basename(out):26s} {n:>4d} rows  (from {src_count} per-type files)")
        types = ", ".join(f"{st} {c}" for st, c in sorted(review_counts.items()))
        print(f"  ✓ {os.path.basename(review_out):26s} {n:>4d} rows  "
              f"(review copy, one sheet per sample type)")
        print(f"      {types}")

    # Report on assay-id resolution coverage
    cited = set()
    # Walk the assay titles we actually emitted (from the source files)
    for arm in by_arm:
        for path in by_arm[arm]:
            try:
                # Source files now live in arch after this run
                wb = openpyxl.load_workbook(str(arch / os.path.basename(path)),
                                            data_only=True)
                if "Assay" in wb.sheetnames:
                    for r in wb["Assay"].iter_rows(min_row=2, values_only=True):
                        if r and len(r) >= 3 and r[2]:
                            candidate = str(r[2]).strip()
                            if candidate and not candidate.startswith("("):
                                cited.add(candidate)
                                break
                wb.close()
            except FileNotFoundError:
                pass

    resolved_direct = {t for t in cited if t in lookup}
    resolved_via_synonym = {t for t in cited if t not in lookup
                            and t in synonyms
                            and synonyms[t] in lookup}
    resolved = resolved_direct | resolved_via_synonym
    unresolved = sorted(cited - resolved)

    print(f"\nAssay-ID resolution: {len(resolved)}/{len(cited)} cited titles resolved "
          f"({len(resolved_direct)} direct + {len(resolved_via_synonym)} via synonym).")
    if resolved_via_synonym:
        print("  Via synonym map:")
        for t in sorted(resolved_via_synonym):
            print(f"    - {t!r} → {synonyms[t]!r} (id {lookup[synonyms[t]]})")
    if unresolved:
        print("  Unresolved (assay_ids column will be blank for rows citing these):")
        for t in unresolved:
            print(f"    - {t!r}")
        print("  → Either re-run `scripts/nextseek_api.py fetch-assays --project-id <id>` "
              "to refresh the cache,")
        print("    or add an entry to context/assay_synonyms.json under "
              "synonyms_by_cited_name.")
