#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["openpyxl>=3.1"]
# ///
"""
Consolidate the 20 per-sample-type 4-sheet xlsx files in assay_sheets/ into
5 per-arm flat-format xlsx files for NExtSEEK batch upload.

Per /nextseek_api/batch-upload/start/ spec:

  Flat Format (single sheet):
    - uid              -- Sample UID. Leave empty for auto-generation.
    - sampletype       -- Sample type name (alias: sample_type)
    - json_metadata    -- JSON metadata string with all sample attributes
    - assay_ids        -- Comma-separated assay IDs (alias: assayids)
    - Optional: project_id, study_title, study_id, sop_id, assay_titles

  When file has all 4 sheet names (Instructions/Samples/Assay/Ontology),
  the 4-sheet format is auto-detected; otherwise flat. Multiple sample types
  in one file are ONLY allowed in flat format.

Output (5 files):
  ArmA.xlsx — 117 rows: RNA, DNA, D.SEQ, D.MSP (phospho), D.IMG (H&E)
  ArmB.xlsx —  74 rows: CEL, MUS, TIS, D.MSP (mouse cell-line MHC)
  ArmE.xlsx —  78 rows: PAT, PAV, TIS, CEL, MUS, D.MSP (human PDX)
  ArmF.xlsx —  96 rows: PAT, PAV, TIS, D.MSP (human patient)
  ArmH.xlsx —   2 rows: D.REF (SDA databases)

Each output file contains one "Samples" sheet with columns:
  - uid, sampletype                         (required by NExtSEEK)
  - name, parent                            (denormalized, for at-a-glance review;
                                             NExtSEEK ignores these as unknown columns)
  - notes_summary                           (denormalized, first 80 chars of Notes)
  - json_metadata                           (canonical upload payload — all sample
                                             attributes serialized as compact JSON)
  - assay_titles                            (parent assay name from the original
                                             4-sheet Assay tab)

The 20 original per-sample-type xlsx files are moved to
  assay_sheets/4sheet_originals/
for reference (in case the schema-level review benefits from the per-type
Instructions docs).
"""

import os
import json
import shutil
from pathlib import Path
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from collections import defaultdict

REPO = str(Path(__file__).resolve().parent.parent)
SRC  = os.path.join(REPO, "assay_sheets")
ARCH = os.path.join(SRC, "4sheet_originals")

HDR_FILL = PatternFill("solid", fgColor="D9E1F2")
HDR_FONT = Font(bold=True)

# Assay-ID resolution: two layers.
#
#  1. context/assay_ids_cache.json — auto-generated by
#     `scripts/nextseek_api.py fetch-assays --project-id <ID>`.
#     Maps {assay_title: assay_id} as actually registered in the target
#     project. Refresh whenever switching projects or when the project's
#     assay catalog changes.
#
#  2. context/assay_synonyms.json — CURATED by an LLM/human after each
#     cache refresh. Maps {cited_assay_name: project_actual_name} for
#     cases where our build scripts use a generic semantic name (e.g.
#     "Mass Spectrometry Proteomics") but the project catalog uses a
#     different title (e.g. "Proteomics"). Reasoning lives in the JSON's
#     _notes block.
#
# Resolution order for any cited assay title:
#   (a) direct hit in the cache
#   (b) apply synonym → re-hit cache
#   (c) leave assay_ids blank (assay_titles still emitted)
#
# Assay IDs are PROJECT-SCOPED — the same title maps to different IDs
# across projects. Always re-run the fetch + re-review synonyms when
# switching projects. See Q S3 in QUESTIONS_FOR_YUFEI.md.

_CACHE_PATH = os.path.join(REPO, "context", "assay_ids_cache.json")
_SYNONYMS_PATH = os.path.join(REPO, "context", "assay_synonyms.json")


def _load_assay_id_lookup():
    """Returns (lookup_dict, synonyms_dict, source_description)."""
    lookup = {}
    synonyms = {}
    sources = []

    if os.path.exists(_CACHE_PATH):
        try:
            with open(_CACHE_PATH) as f:
                cache = json.load(f)
            lookup = cache.get("assay_id_by_title") or {}
            sources.append(f"cache {os.path.basename(_CACHE_PATH)} "
                           f"(project {cache.get('project_id')!r}, "
                           f"{len(lookup)} assays, fetched "
                           f"{cache.get('fetched_at_utc', '?')})")
        except (OSError, json.JSONDecodeError) as e:
            sources.append(f"cache UNREADABLE: {e}")
    else:
        sources.append("no cache (run scripts/nextseek_api.py fetch-assays)")

    if os.path.exists(_SYNONYMS_PATH):
        try:
            with open(_SYNONYMS_PATH) as f:
                syn_doc = json.load(f)
            synonyms = syn_doc.get("synonyms_by_cited_name") or {}
            sources.append(f"synonyms {os.path.basename(_SYNONYMS_PATH)} "
                           f"({len(synonyms)} mappings)")
        except (OSError, json.JSONDecodeError) as e:
            sources.append(f"synonyms UNREADABLE: {e}")
    else:
        sources.append("no synonyms file")

    return lookup, synonyms, " + ".join(sources)


ASSAY_ID_LOOKUP, ASSAY_SYNONYMS, _ASSAY_ID_SOURCE = _load_assay_id_lookup()


def resolve_assay_id(cited_name: str):
    """Resolve a cited assay title to (resolved_title, assay_id_or_None).

    `resolved_title` is what we emit in the `assay_titles` column; either
    the cited name (if found directly in cache) or the synonym (if mapped).
    """
    if not cited_name:
        return "", None
    if cited_name in ASSAY_ID_LOOKUP:
        return cited_name, ASSAY_ID_LOOKUP[cited_name]
    if cited_name in ASSAY_SYNONYMS:
        canonical = ASSAY_SYNONYMS[cited_name]
        if canonical in ASSAY_ID_LOOKUP:
            return canonical, ASSAY_ID_LOOKUP[canonical]
    # No mapping; emit cited title with no ID (upload tool can flag or admin can patch)
    return cited_name, None

# ─── Read one 4-sheet xlsx → flat records ──────────────────────────────────

def read_4sheet(path):
    """Return (sampletype, [records]) — records are dicts of column→value."""
    wb = openpyxl.load_workbook(path, data_only=True)

    # Sample type from Instructions sheet (Database Field has 'SampleType::AttrName')
    instr = wb["Instructions"]
    sampletype = None
    for r in instr.iter_rows(min_row=2, values_only=True):
        if r and len(r) > 1 and r[1]:
            sampletype = str(r[1]).split("::")[0]
            break

    # Parent assay (first row of Assay sheet). Ignore parenthesized placeholders
    # like "(visit registration)" — those aren't real NExtSEEK assay names.
    #
    # Two schemas in the wild:
    #   CSBC:       columns = (SampleType, Role, AssayTitle, ...)  with Role=='Parent'
    #   IntravChip: columns = (SampleType, AssayType, Assay, Direction) with
    #               Direction=='child' (the sample is a child of the assay)
    # In both cases the assay title is in column[2]; the IntravChip files don't
    # have a 'Parent' literal anywhere, so we accept either ('Parent' in col 1)
    # or any row whose col 2 is a real assay name.
    parent_assay = ""
    if "Assay" in wb.sheetnames:
        for r in wb["Assay"].iter_rows(min_row=2, values_only=True):
            if r and len(r) >= 3 and r[2]:
                candidate = str(r[2]).strip()
                if candidate and not candidate.startswith("("):
                    parent_assay = candidate
                    break

    # Sample rows
    samples = wb["Samples"]
    rows_iter = samples.iter_rows(values_only=True)
    headers = next(rows_iter)
    records = []
    for r in rows_iter:
        if not any(v not in (None, "") for v in r):
            continue
        rec = {h: v for h, v in zip(headers, r) if v not in (None, "")}
        records.append(rec)

    wb.close()
    return sampletype, parent_assay, records

# ─── Build one flat-format xlsx for an arm ─────────────────────────────────

def build_arm_flat(arm_name, source_files):
    """source_files: list of (sampletype, parent_assay, [records])."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Samples"

    flat_cols = ["uid", "sampletype", "name", "parent",
                 "notes_summary", "assay_titles", "assay_ids", "json_metadata"]
    ws.append(flat_cols)
    for cell in ws[1]:
        cell.fill = HDR_FILL
        cell.font = HDR_FONT

    total = 0
    for sampletype, parent_assay, records in source_files:
        # Resolve cited assay title → (canonical title, ID) via cache+synonyms
        resolved_title, assay_id_val = resolve_assay_id(parent_assay)
        assay_ids_cell = str(assay_id_val) if assay_id_val is not None else ""

        for rec in records:
            # NExtSEEK expects UID inside json_metadata (verified by validate
            # endpoint dry-run). Keep it in the dict; ALSO emit at the
            # top-level `uid` column so both shapes are populated.
            uid = rec.get("UID", "")
            name = rec.get("Name", "")
            parent = rec.get("Parent", "")
            notes = rec.get("Notes", "")
            notes_summary = (notes[:80] + "…") if len(str(notes)) > 80 else notes

            # json_metadata: all attributes as compact JSON (INCLUDING UID)
            json_meta = json.dumps(rec, separators=(",", ":"), default=str)

            ws.append([uid, sampletype, name, parent, notes_summary,
                       resolved_title, assay_ids_cell, json_meta])
            total += 1

    # Column widths tuned for readability
    widths = {"uid": 24, "sampletype": 12, "name": 30, "parent": 24,
              "notes_summary": 50, "assay_titles": 30, "assay_ids": 10,
              "json_metadata": 80}
    for i, col in enumerate(flat_cols, 1):
        ws.column_dimensions[get_column_letter(i)].width = widths.get(col, 16)

    # Wrap notes_summary so the row doesn't blow up
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)

    # README sheet — quick orientation
    readme = wb.create_sheet("README")
    readme.append(["NExtSEEK batch upload — flat format"])
    readme.append([])
    readme.append([f"Arm: {arm_name}"])
    readme.append([f"Total rows: {total}"])
    readme.append([f"Sample types: {', '.join(st for st, _, _ in source_files)}"])
    readme.append([])
    readme.append(["Columns:"])
    readme.append(["  uid             — pre-assigned UID (NExtSEEK will validate)"])
    readme.append(["  sampletype      — NExtSEEK sample-type short code (MUS, TIS, RNA, D.SEQ, …)"])
    readme.append(["  name            — DENORMALIZED for review; same as json_metadata['Name']"])
    readme.append(["  parent          — DENORMALIZED for review; same as json_metadata['Parent']"])
    readme.append(["  notes_summary   — DENORMALIZED first 80 chars of json_metadata['Notes']"])
    readme.append(["  assay_titles    — Parent assay name (human-readable)"])
    readme.append(["  assay_ids       — Internal Assay ID where available in local assays_db.json"])
    readme.append(["                    (RNA Extraction=61, Tissue Collection=74, Short Read Sequencing=64,"])
    readme.append(["                     Cell Culture=85; others blank — see Q S3 in QUESTIONS_FOR_YUFEI.md)"])
    readme.append(["  json_metadata   — UPLOAD PAYLOAD: full per-sample attributes as compact JSON"])
    readme.append([])
    readme.append(["NOTE: NExtSEEK reads uid, sampletype, json_metadata, plus EITHER assay_ids OR"])
    readme.append(["      assay_titles (both are in the InputRowModel schema, but the spec does NOT"])
    readme.append(["      explicitly say whether the server auto-resolves titles → IDs). Both columns"])
    readme.append(["      are included here; the upload tool can use whichever it prefers and the"])
    readme.append(["      unused one is ignored (per the 'unknown columns ignored with warning' rule)."])
    readme.append(["      The denormalized columns (name/parent/notes_summary) are for human review"])
    readme.append(["      only and are also silently ignored on upload."])
    readme.column_dimensions['A'].width = 100
    for cell in readme['A']:
        cell.alignment = Alignment(wrap_text=True)
    readme['A1'].font = Font(bold=True, size=14)

    out = os.path.join(SRC, f"{arm_name}.xlsx")
    wb.save(out)
    return out, total

# ─── Main ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--all-in-one", metavar="NAME", default=None,
        help="Consolidate ALL 4-sheet inputs into a single flat output named "
             "NAME.xlsx, rather than grouping by filename prefix (the default "
             "per-arm CSBC behavior). Use this for single-project uploads "
             "(e.g. --all-in-one IntravChip_upload).",
    )
    args = parser.parse_args()

    print(f"Assay-ID source: {_ASSAY_ID_SOURCE}\n")

    # Source dir resolution: prefer 4sheet_originals/ if it exists with files
    # (subsequent runs), otherwise read from assay_sheets/ root (first run).
    # Only pick up files that look like 4-sheet sources (have an underscore in
    # the filename, e.g. ArmA_RNA.xlsx; consolidated outputs like ArmA.xlsx
    # don't have one).
    def is_4sheet_filename(name):
        return name.endswith(".xlsx") and not name.startswith("~") and "_" in name

    if os.path.isdir(ARCH) and any(is_4sheet_filename(f) for f in os.listdir(ARCH)):
        source_dir = ARCH
        print(f"Reading 4-sheet sources from {ARCH}/ (archive)")
    else:
        source_dir = SRC
        print(f"Reading 4-sheet sources from {SRC}/ (first-run mode)")

    files = sorted(f for f in os.listdir(source_dir) if is_4sheet_filename(f))
    if not files:
        print(f"  ERROR: no 4-sheet files found in {source_dir}", file=__import__("sys").stderr)
        raise SystemExit(1)

    by_arm = defaultdict(list)  # 'ArmA' → [(path, ...)]
    if args.all_in_one:
        # Single-bucket mode: every input feeds the same output.
        for f in files:
            by_arm[args.all_in_one].append(os.path.join(source_dir, f))
    else:
        for f in files:
            arm = f.split("_")[0]
            by_arm[arm].append(os.path.join(source_dir, f))

    # Clean any prior consolidated outputs so we don't mix old + new
    for f in os.listdir(SRC):
        if f.endswith(".xlsx") and "_" not in f:
            os.remove(os.path.join(SRC, f))

    # Archive originals (only if reading from SRC root; otherwise they're already archived)
    os.makedirs(ARCH, exist_ok=True)
    if source_dir == SRC:
        print(f"Archiving {len(files)} four-sheet originals to {ARCH}/")
    print()

    arm_outputs = []
    for arm in sorted(by_arm):
        # Load all sub-files for this arm
        sources = []
        for path in by_arm[arm]:
            st, pa, recs = read_4sheet(path)
            sources.append((st, pa, recs))
        # Build consolidated flat file
        out, n = build_arm_flat(arm, sources)
        arm_outputs.append((out, n, len(by_arm[arm])))

    # Move originals to archive AFTER reading (only if we read from SRC root —
    # otherwise they're already in ARCH).
    if source_dir == SRC:
        for f in files:
            shutil.move(os.path.join(SRC, f), os.path.join(ARCH, f))

    print("Consolidated:")
    for out, n, src_count in arm_outputs:
        print(f"  ✓ {os.path.basename(out):20s} {n:>4d} rows  (from {src_count} per-type files)")

    # Report on assay-id resolution coverage
    cited = set()
    for arm in by_arm:
        for path in by_arm[arm]:
            # (re-read just the Assay sheet — cheap, already done above; this
            # is just for the report)
            pass
    # Walk the assay titles we actually emitted (from the source files)
    for arm in by_arm:
        for path in by_arm[arm]:
            try:
                # Source files now live in ARCH after this run
                wb = openpyxl.load_workbook(os.path.join(ARCH, os.path.basename(path)),
                                            data_only=True)
                if "Assay" in wb.sheetnames:
                    for r in wb["Assay"].iter_rows(min_row=2, values_only=True):
                        if r and len(r) >= 3 and r[2]:
                            candidate = str(r[2]).strip()
                            if candidate and not candidate.startswith("("):
                                cited.add(candidate)
                                break
                wb.close()
            except FileNotFoundError:
                pass

    resolved_direct = {t for t in cited if t in ASSAY_ID_LOOKUP}
    resolved_via_synonym = {t for t in cited if t not in ASSAY_ID_LOOKUP
                            and t in ASSAY_SYNONYMS
                            and ASSAY_SYNONYMS[t] in ASSAY_ID_LOOKUP}
    resolved = resolved_direct | resolved_via_synonym
    unresolved = sorted(cited - resolved)

    print(f"\nAssay-ID resolution: {len(resolved)}/{len(cited)} cited titles resolved "
          f"({len(resolved_direct)} direct + {len(resolved_via_synonym)} via synonym).")
    if resolved_via_synonym:
        print("  Via synonym map:")
        for t in sorted(resolved_via_synonym):
            print(f"    - {t!r} → {ASSAY_SYNONYMS[t]!r} (id {ASSAY_ID_LOOKUP[ASSAY_SYNONYMS[t]]})")
    if unresolved:
        print("  Unresolved (assay_ids column will be blank for rows citing these):")
        for t in unresolved:
            print(f"    - {t!r}")
        print("  → Either re-run `scripts/nextseek_api.py fetch-assays --project-id <id>` "
              "to refresh the cache,")
        print("    or add an entry to context/assay_synonyms.json under "
              "synonyms_by_cited_name.")
